# Generated by Django 5.2 on 2025-05-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchedstock',
            options={'ordering': ['-added_at'], 'verbose_name': 'Отслеживаемая акция', 'verbose_name_plural': 'Отслеживаемые акции'},
        ),
    ]
