# Generated by Django 5.2 on 2025-06-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_contact_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
    ]
