# Generated by Django 5.2 on 2025-06-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='type',
            field=models.CharField(choices=[('pro', 'PRO'), ('plus', 'PLUS')], default='pro', max_length=10),
        ),
    ]
