# Generated by Django 5.2 on 2025-05-13 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShariahScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_date', models.DateField()),
                ('result_status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-compliant'), ('doubtful', 'Doubtful'), ('forbidden', 'Forbidden')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('exchange', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('currency', models.CharField(max_length=10)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=150, null=True)),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-compliant'), ('doubtful', 'Doubtful'), ('forbidden', 'Forbidden')], default='doubtful', max_length=20)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('trading_view_ticker', models.CharField(blank=True, max_length=50, null=True)),
                ('tinkoff_link', models.URLField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('income', 'Income'), ('debt', 'Debt'), ('deposits', 'Deposits'), ('halal', 'Halal Activities'), ('other', 'Other')], max_length=50)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-compliant'), ('doubtful', 'Doubtful'), ('forbidden', 'Forbidden')], max_length=20)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='stocks.shariahscreening')),
            ],
        ),
        migrations.AddField(
            model_name='shariahscreening',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='stocks.stock'),
        ),
        migrations.CreateModel(
            name='ComplianceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-compliant'), ('doubtful', 'Doubtful'), ('forbidden', 'Forbidden')], max_length=20)),
                ('date', models.DateField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='stocks.stock')),
            ],
        ),
    ]
