# Generated by Django 5.2 on 2025-05-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compliancecriteria',
            options={'verbose_name': 'Критерий соответствия', 'verbose_name_plural': 'Критерии соответствия'},
        ),
        migrations.AlterModelOptions(
            name='compliancestatushistory',
            options={'verbose_name': 'История статуса', 'verbose_name_plural': 'Истории статуса'},
        ),
        migrations.AlterModelOptions(
            name='shariahscreening',
            options={'verbose_name': 'Шариатская проверка', 'verbose_name_plural': 'Шариатские проверки'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
    ]
