# Generated by Django 5.2 on 2025-06-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_compliancecriteria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_free_access',
            field=models.BooleanField(default=False),
        ),
    ]
